---
- name: create mariadb repo
  template: 
    src: mariadb-el8.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root 
    group: root 
    mode: 0644

- name: Install Mariadb packages
  dnf:
    name: mariadb-server
    state: installed

- name: Install additional packages
  dnf:
    name:
    - python3
    - python3-PyMySQL
    state: installed

...
