---
- name: Install packages
  yum:
    name: "{{ vars['mariadb_packages_' + ( ansible_distribution | lower ) + ( ansible_distribution_major_version | lower ) ] }}" 
    state: installed

- name: update custom mariadb server configuration
  template:
    src: custom.cnf.j2
    dest: /etc/my.cnf.d/custom.cnf
    owner: root
    group: root
    mode: 0644

- name: Enable and start mariadb-server
  service:
    name: mariadb
    state: started
    enabled: yes

...
