---

- name: deploy repo file
  copy:
    src: mariadb.repo
    dest: /etc/yum.repos.d/mariadb.repo

- name: Install packages
  yum:
    name: "{{ mariadb_packages + mariadb_packages_centos7 }}" 
    state: installed

...
