---
- name: disable mysql community release
  ansible.builtin.dnf:
    name: mysql*-community-release
    state: absent

- name: disable mariadb appstream module
  ansible.builtin.lineinfile:
    path: /etc/dnf/modules.d/mariadb.module
    regexp: '^state=.*'
    line: state=disabled
    create: no
  failed_when: False

- name: create mariadb repo
  ansible.builtin.template:
    src: mariadb.repo.j2
    dest: /etc/yum.repos.d/mariadb.repo
    owner: root 
    group: root 
    mode: 0644
...
