---
- name: Install Mariadb packages
  dnf:
    name: mariadb-server
    state: installed

- name: Install additional packages
  dnf:
    name:
    - python3
    - python3-PyMySQL
    state: installed
...
