---
- name: Manage Mariadb databases
  mysql_db:
    name: "{{ item.name }}"
    login_unix_socket: /var/lib/mysql/mysql.sock
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ mariadb_databases }}"
...
