---
- name: Create mariadb backup script
  ansible.builtin.template:
    src: backup-mysql.sh.j2
    dest: /usr/local/sbin/backup-mysql.sh
    owner: root 
    group: root 
    mode: 0700
  tags: [backup]

- name: enable crond
  ansible.builtin.systemd:
    name: crond
    enabled: yes
  tags: [backup]

- name: create cronjob for backup
  ansible.builtin.cron:
    name: backup-mysql
    disabled: "{{ not (mariadb_backup_enable | bool) }}"
    minute: 1
    hour: 2
    user: root
    job: /usr/local/sbin/backup-mysql.sh
    cron_file: backup-mysql
  tags: [backup]
...
